services:
  amarillo:
    build:
      context: .
      args:
        PLUGINS: ${AMARILLO_PLUGINS-amarillo-metrics amarillo-grfs-exporter }  
    environment:
    # Configure these for external enhancer and/or generator
    - ENHANCER_URL=${AMARILLO_ENHANCER_URL:-http://enhancer:80} 
    - GENERATOR_URL=${AMARILLO_GENERATOR_URL:-http://generator:80} 

    - ADMIN_TOKEN=${ADMIN_TOKEN?}
    - RIDE2GO_TOKEN=${RIDE2GO_TOKEN-}
    - GRAPHHOPPER_BASE_URL='https://api.mfdz.de/gh'
    # - SECRET_KEY
    # - METRICS_USER
    # - METRICS_PASSWORD
    
    # - MAX_WORKERS=1
    volumes:
    - ./data:/app/data
    ports:
      # - "8002:80"
      - "${PORT:-8002}:80"
  enhancer:
    image: "amarillo-enhancer"
    volumes:
    - ./data:/app/data
    profiles:
      - enhancer
  generator:
    image: "amarillo-grfs-generator"
    volumes:
    - ./data:/app/data
    profiles:
      - generator


#sudo docker compose --profile enhancer up   
#sudo docker compose --profile enhancer --profile generator up   